import { AboutMeType, ConnectType, ProjectType } from "./types";

export const aboutMeData: AboutMeType = {
  start: "Welcome to my portfolio! Here you'll find details about my career and projects.",
  experience:
    "I have been working with web development for several years, focusing on front-end technologies like React, Next.js, and Tailwind CSS.",
  nextStep: "Currently, I am looking to take on more full-stack roles and contribute to impactful open-source projects.",
  purpose: "This site serves as both a showcase of my work and a place where I can connect with other developers and potential collaborators.",
};

export const connectData: ConnectType = {
  connectText: "Feel free to reach out to me for collaborations, questions, or just a friendly chat about web development!",
  imgSrc: "/images/mock-profile.jpg",
  alt: "Profile picture for mock testing",
};

export const mockProjects: ProjectType[] = [
  {
    id: "1",
    title: "Project 1",
    date: "Jan 2022",
    imgSrc: "/images/project1.png",
    alt: "Snapshot of Project 1.",
    description: "This project is about creating a modern, responsive website for a tech startup.",
    githubLink: "https://github.com/example/project-1",
    websiteLink: "https://project-1.com",
    favourite: false,
    techs: ["React", "Next.js", "Tailwind CSS", "Typescript"],
  },
  {
    id: "2",
    title: "Project 2",
    date: "Mar 2022",
    imgSrc: "/images/project2.png",
    alt: "Snapshot of Project 2.",
    description: "A dynamic web app for organizing and tracking personal tasks and goals.",
    githubLink: "https://github.com/example/project-2",
    websiteLink: "https://project-2.com",
    favourite: false,
    techs: ["React", "Next.js", "Tailwind CSS", "Node.js"],
  },
  {
    id: "3",
    title: "Project 3",
    date: "May 2022",
    imgSrc: "/images/project3.png",
    alt: "Snapshot of Project 3.",
    description: "A social media app built to connect users through their favorite activities.",
    githubLink: "https://github.com/example/project-3",
    websiteLink: "https://project-3.com",
    favourite: false,
    techs: ["React", "Next.js", "MongoDB", "Express"],
  },
  {
    id: "4",
    title: "Project 4",
    date: "Jul 2022",
    imgSrc: "/images/project4.png",
    alt: "Snapshot of Project 4.",
    description: "An e-commerce platform for a local clothing brand, featuring product pages and a shopping cart.",
    githubLink: "https://github.com/example/project-4",
    websiteLink: "https://project-4.com",
    favourite: false,
    techs: ["React", "Next.js", "Tailwind CSS", "Firebase"],
  },
  {
    id: "5",
    title: "Project 5",
    date: "Sep 2022",
    imgSrc: "/images/project5.png",
    alt: "Snapshot of Project 5.",
    description: "A content management system (CMS) for managing blog posts, comments, and user profiles.",
    githubLink: "https://github.com/example/project-5",
    websiteLink: "https://project-5.com",
    favourite: false,
    techs: ["React", "Next.js", "GraphQL", "Apollo"],
  },
  {
    id: "6",
    title: "Project 6",
    date: "Nov 2022",
    imgSrc: "/images/project6.png",
    alt: "Snapshot of Project 6.",
    description: "A weather forecasting app that shows real-time weather data from different locations.",
    githubLink: "https://github.com/example/project-6",
    websiteLink: "https://project-6.com",
    favourite: false,
    techs: ["React", "Next.js", "Tailwind CSS", "OpenWeather API"],
  },
  {
    id: "7",
    title: "Project 7",
    date: "Dec 2022",
    imgSrc: "/images/project7.png",
    alt: "Snapshot of Project 7.",
    description: "A personal finance tracker that helps users budget, track expenses, and set financial goals.",
    githubLink: "https://github.com/example/project-7",
    websiteLink: "https://project-7.com",
    favourite: false,
    techs: ["React", "Next.js", "MongoDB", "Tailwind CSS"],
  },
];
